# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import messages_pb2 as messages__pb2


class TextMessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientSendMessage = channel.unary_unary(
                '/grpc_example.TextMessageService/ClientSendMessage',
                request_serializer=messages__pb2.TextMessage.SerializeToString,
                response_deserializer=messages__pb2.TextMessage.FromString,
                )


class TextMessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClientSendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextMessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientSendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientSendMessage,
                    request_deserializer=messages__pb2.TextMessage.FromString,
                    response_serializer=messages__pb2.TextMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_example.TextMessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TextMessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClientSendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_example.TextMessageService/ClientSendMessage',
            messages__pb2.TextMessage.SerializeToString,
            messages__pb2.TextMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
