# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import communication_service_pb2 as communication__service__pb2


class CommunicationServiceStub(object):
    """communication_service.proto
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDroneUpdate = channel.stream_unary(
                '/CommunicationService/SendDroneUpdate',
                request_serializer=communication__service__pb2.DroneUpdate.SerializeToString,
                response_deserializer=communication__service__pb2.Response.FromString,
                )
        self.SendMission = channel.unary_unary(
                '/CommunicationService/SendMission',
                request_serializer=communication__service__pb2.Mission.SerializeToString,
                response_deserializer=communication__service__pb2.Response.FromString,
                )


class CommunicationServiceServicer(object):
    """communication_service.proto
    """

    def SendDroneUpdate(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDroneUpdate': grpc.stream_unary_rpc_method_handler(
                    servicer.SendDroneUpdate,
                    request_deserializer=communication__service__pb2.DroneUpdate.FromString,
                    response_serializer=communication__service__pb2.Response.SerializeToString,
            ),
            'SendMission': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMission,
                    request_deserializer=communication__service__pb2.Mission.FromString,
                    response_serializer=communication__service__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CommunicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommunicationService(object):
    """communication_service.proto
    """

    @staticmethod
    def SendDroneUpdate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/CommunicationService/SendDroneUpdate',
            communication__service__pb2.DroneUpdate.SerializeToString,
            communication__service__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CommunicationService/SendMission',
            communication__service__pb2.Mission.SerializeToString,
            communication__service__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
