# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63ommunication_service.proto\"4\n\x0b\x44roneUpdate\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\t\x12\x13\n\x0bupdate_data\x18\x02 \x01(\t\"1\n\x07Mission\x12\x10\n\x08\x64rone_id\x18\x01 \x01(\t\x12\x14\n\x0cmission_data\x18\x02 \x01(\t\"\x18\n\x08Response\x12\x0c\n\x04text\x18\x01 \x01(\t2h\n\x14\x43ommunicationService\x12,\n\x0fSendDroneUpdate\x12\x0c.DroneUpdate\x1a\t.Response(\x01\x12\"\n\x0bSendMission\x12\x08.Mission\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DRONEUPDATE']._serialized_start=31
  _globals['_DRONEUPDATE']._serialized_end=83
  _globals['_MISSION']._serialized_start=85
  _globals['_MISSION']._serialized_end=134
  _globals['_RESPONSE']._serialized_start=136
  _globals['_RESPONSE']._serialized_end=160
  _globals['_COMMUNICATIONSERVICE']._serialized_start=162
  _globals['_COMMUNICATIONSERVICE']._serialized_end=266
# @@protoc_insertion_point(module_scope)
