# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import uav_communicator_pb2 as uav__communicator__pb2


class CommunicationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendStatusUpdate = channel.unary_unary(
                '/UavCommunicator.CommunicationService/SendStatusUpdate',
                request_serializer=uav__communicator__pb2.StatusUpdate.SerializeToString,
                response_deserializer=uav__communicator__pb2.response.FromString,
                )
        self.SendFlyToDestination = channel.unary_unary(
                '/UavCommunicator.CommunicationService/SendFlyToDestination',
                request_serializer=uav__communicator__pb2.FlyToDestination.SerializeToString,
                response_deserializer=uav__communicator__pb2.response.FromString,
                )


class CommunicationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendStatusUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFlyToDestination(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendStatusUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendStatusUpdate,
                    request_deserializer=uav__communicator__pb2.StatusUpdate.FromString,
                    response_serializer=uav__communicator__pb2.response.SerializeToString,
            ),
            'SendFlyToDestination': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFlyToDestination,
                    request_deserializer=uav__communicator__pb2.FlyToDestination.FromString,
                    response_serializer=uav__communicator__pb2.response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UavCommunicator.CommunicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommunicationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendStatusUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UavCommunicator.CommunicationService/SendStatusUpdate',
            uav__communicator__pb2.StatusUpdate.SerializeToString,
            uav__communicator__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendFlyToDestination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UavCommunicator.CommunicationService/SendFlyToDestination',
            uav__communicator__pb2.FlyToDestination.SerializeToString,
            uav__communicator__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
