# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommunication.proto\x12\rcommunication\"\x1f\n\x07Mission\x12\x14\n\x0cmission_data\x18\x01 \x01(\t\"<\n\x06Status\x12\x10\n\x08latitude\x18\x01 \x01(\t\x12\x11\n\tlongitude\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\"\x1e\n\x0b\x41\x63knowledge\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9a\x01\n\x14\x43ommunicationService\x12\x41\n\x0bSendMission\x12\x16.communication.Mission\x1a\x1a.communication.Acknowledge\x12?\n\nSendStatus\x12\x15.communication.Status\x1a\x1a.communication.Acknowledgeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MISSION']._serialized_start=38
  _globals['_MISSION']._serialized_end=69
  _globals['_STATUS']._serialized_start=71
  _globals['_STATUS']._serialized_end=131
  _globals['_ACKNOWLEDGE']._serialized_start=133
  _globals['_ACKNOWLEDGE']._serialized_end=163
  _globals['_COMMUNICATIONSERVICE']._serialized_start=166
  _globals['_COMMUNICATIONSERVICE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
