# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculation_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63\x61lculation_service.proto\x12\x0cgrpc_example\"3\n\x0eRequestMessage\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\x01\"!\n\x0fResponseMessage\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32h\n\x10\x43\x61lculateService\x12T\n\x15\x63\x61lculate_square_root\x12\x1c.grpc_example.RequestMessage\x1a\x1d.grpc_example.ResponseMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculation_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTMESSAGE']._serialized_start=43
  _globals['_REQUESTMESSAGE']._serialized_end=94
  _globals['_RESPONSEMESSAGE']._serialized_start=96
  _globals['_RESPONSEMESSAGE']._serialized_end=129
  _globals['_CALCULATESERVICE']._serialized_start=131
  _globals['_CALCULATESERVICE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
